export const countries = [
  { code: "AF", name: "Afghanistan" },
  { code: "AL", name: "Albania" },
  { code: "DZ", name: "Algeria" },
  { code: "AS", name: "American Samoa" },
  { code: "AD", name: "Andorra" },
  { code: "AO", name: "Angola" },
  { code: "AI", name: "Anguilla" },
  { code: "AQ", name: "Antarctica" },
  { code: "AG", name: "Antigua and Barbuda" },
  { code: "AR", name: "Argentina" },
  { code: "AM", name: "Armenia" },
  { code: "AW", name: "Aruba" },
  { code: "AU", name: "Australia" },
  { code: "AT", name: "Austria" },
  { code: "AZ", name: "Azerbaijan" },

  { code: "BS", name: "Bahamas" },
  { code: "BH", name: "Bahrain" },
  { code: "BD", name: "Bangladesh" },
  { code: "BB", name: "Barbados" },
  { code: "BY", name: "Belarus" },
  { code: "BE", name: "Belgium" },
  { code: "BZ", name: "Belize" },
  { code: "BJ", name: "Benin" },
  { code: "BM", name: "Bermuda" },
  { code: "BT", name: "Bhutan" },
  { code: "BO", name: "Bolivia" },
  { code: "BA", name: "Bosnia and Herzegovina" },
  { code: "BW", name: "Botswana" },
  { code: "BR", name: "Brazil" },
  { code: "IO", name: "British Indian Ocean Territory" },
  { code: "BN", name: "Brunei Darussalam" },
  { code: "BG", name: "Bulgaria" },
  { code: "BF", name: "Burkina Faso" },
  { code: "BI", name: "Burundi" },

  { code: "KH", name: "Cambodia" },
  { code: "CM", name: "Cameroon" },
  { code: "CA", name: "Canada" },
  { code: "CV", name: "Cape Verde" },
  { code: "KY", name: "Cayman Islands" },
  { code: "CF", name: "Central African Republic" },
  { code: "TD", name: "Chad" },
  { code: "CL", name: "Chile" },
  { code: "CN", name: "China" },
  { code: "CX", name: "Christmas Island" },
  { code: "CC", name: "Cocos (Keeling) Islands" },
  { code: "CO", name: "Colombia" },
  { code: "KM", name: "Comoros" },
  { code: "CG", name: "Congo" },
  { code: "CD", name: "Congo, Democratic Republic" },
  { code: "CK", name: "Cook Islands" },
  { code: "CR", name: "Costa Rica" },
  { code: "CI", name: "Côte d'Ivoire" },
  { code: "HR", name: "Croatia" },
  { code: "CU", name: "Cuba" },
  { code: "CY", name: "Cyprus" },
  { code: "CZ", name: "Czech Republic" },

  { code: "DK", name: "Denmark" },
  { code: "DJ", name: "Djibouti" },
  { code: "DM", name: "Dominica" },
  { code: "DO", name: "Dominican Republic" },

  { code: "EC", name: "Ecuador" },
  { code: "EG", name: "Egypt" },
  { code: "SV", name: "El Salvador" },
  { code: "GQ", name: "Equatorial Guinea" },
  { code: "ER", name: "Eritrea" },
  { code: "EE", name: "Estonia" },
  { code: "SZ", name: "Eswatini" },
  { code: "ET", name: "Ethiopia" },

  { code: "FJ", name: "Fiji" },
  { code: "FI", name: "Finland" },
  { code: "FR", name: "France" },

  { code: "GA", name: "Gabon" },
  { code: "GM", name: "Gambia" },
  { code: "GE", name: "Georgia" },
  { code: "DE", name: "Germany" },
  { code: "GH", name: "Ghana" },
  { code: "GI", name: "Gibraltar" },
  { code: "GR", name: "Greece" },
  { code: "GL", name: "Greenland" },
  { code: "GD", name: "Grenada" },
  { code: "GU", name: "Guam" },
  { code: "GT", name: "Guatemala" },
  { code: "GG", name: "Guernsey" },
  { code: "GN", name: "Guinea" },
  { code: "GW", name: "Guinea-Bissau" },
  { code: "GY", name: "Guyana" },

  { code: "HT", name: "Haiti" },
  { code: "HN", name: "Honduras" },
  { code: "HK", name: "Hong Kong" },
  { code: "HU", name: "Hungary" },

  { code: "IS", name: "Iceland" },
  { code: "IN", name: "India" },
  { code: "ID", name: "Indonesia" },
  { code: "IR", name: "Iran" },
  { code: "IQ", name: "Iraq" },
  { code: "IE", name: "Ireland" },
  { code: "IM", name: "Isle of Man" },
  { code: "IL", name: "Israel" },
  { code: "IT", name: "Italy" },

  { code: "JM", name: "Jamaica" },
  { code: "JP", name: "Japan" },
  { code: "JE", name: "Jersey" },
  { code: "JO", name: "Jordan" },

  { code: "KZ", name: "Kazakhstan" },
  { code: "KE", name: "Kenya" },
  { code: "KI", name: "Kiribati" },
  { code: "KP", name: "Korea, North" },
  { code: "KR", name: "Korea, South" },
  { code: "KW", name: "Kuwait" },
  { code: "KG", name: "Kyrgyzstan" },

  { code: "LA", name: "Laos" },
  { code: "LV", name: "Latvia" },
  { code: "LB", name: "Lebanon" },
  { code: "LS", name: "Lesotho" },
  { code: "LR", name: "Liberia" },
  { code: "LY", name: "Libya" },
  { code: "LI", name: "Liechtenstein" },
  { code: "LT", name: "Lithuania" },
  { code: "LU", name: "Luxembourg" },

  { code: "MO", name: "Macau" },
  { code: "MG", name: "Madagascar" },
  { code: "MW", name: "Malawi" },
  { code: "MY", name: "Malaysia" },
  { code: "MV", name: "Maldives" },
  { code: "ML", name: "Mali" },
  { code: "MT", name: "Malta" },
  { code: "MH", name: "Marshall Islands" },
  { code: "MQ", name: "Martinique" },
  { code: "MR", name: "Mauritania" },
  { code: "MU", name: "Mauritius" },
  { code: "MX", name: "Mexico" },
  { code: "FM", name: "Micronesia" },
  { code: "MD", name: "Moldova" },
  { code: "MC", name: "Monaco" },
  { code: "MN", name: "Mongolia" },
  { code: "ME", name: "Montenegro" },
  { code: "MS", name: "Montserrat" },
  { code: "MA", name: "Morocco" },
  { code: "MZ", name: "Mozambique" },
  { code: "MM", name: "Myanmar" },

  { code: "NA", name: "Namibia" },
  { code: "NR", name: "Nauru" },
  { code: "NP", name: "Nepal" },
  { code: "NL", name: "Netherlands" },
  { code: "NZ", name: "New Zealand" },
  { code: "NI", name: "Nicaragua" },
  { code: "NE", name: "Niger" },
  { code: "NG", name: "Nigeria" },
  { code: "NU", name: "Niue" },
  { code: "NF", name: "Norfolk Island" },
  { code: "MK", name: "North Macedonia" },
  { code: "MP", name: "Northern Mariana Islands" },
  { code: "NO", name: "Norway" },

  { code: "OM", name: "Oman" },

  { code: "PK", name: "Pakistan" },
  { code: "PW", name: "Palau" },
  { code: "PS", name: "Palestine" },
  { code: "PA", name: "Panama" },
  { code: "PG", name: "Papua New Guinea" },
  { code: "PY", name: "Paraguay" },
  { code: "PE", name: "Peru" },
  { code: "PH", name: "Philippines" },
  { code: "PL", name: "Poland" },
  { code: "PT", name: "Portugal" },

  { code: "PR", name: "Puerto Rico" },

  { code: "QA", name: "Qatar" },

  { code: "RE", name: "Reunion" },
  { code: "RO", name: "Romania" },
  { code: "RU", name: "Russia" },
  { code: "RW", name: "Rwanda" },

  { code: "WS", name: "Samoa" },
  { code: "SM", name: "San Marino" },
  { code: "ST", name: "Sao Tome and Principe" },
  { code: "SA", name: "Saudi Arabia" },
  { code: "SN", name: "Senegal" },
  { code: "RS", name: "Serbia" },
  { code: "SC", name: "Seychelles" },
  { code: "SL", name: "Sierra Leone" },
  { code: "SG", name: "Singapore" },
  { code: "SK", name: "Slovakia" },
  { code: "SI", name: "Slovenia" },
  { code: "SB", name: "Solomon Islands" },
  { code: "SO", name: "Somalia" },
  { code: "ZA", name: "South Africa" },
  { code: "GS", name: "South Georgia and Sandwich Islands" },
  { code: "SS", name: "South Sudan" },
  { code: "ES", name: "Spain" },
  { code: "LK", name: "Sri Lanka" },
  { code: "SD", name: "Sudan" },
  { code: "SR", name: "Suriname" },
  { code: "SE", name: "Sweden" },
  { code: "CH", name: "Switzerland" },
  { code: "SY", name: "Syria" },

  { code: "TW", name: "Taiwan" },
  { code: "TJ", name: "Tajikistan" },
  { code: "TZ", name: "Tanzania" },
  { code: "TH", name: "Thailand" },
  { code: "TL", name: "Timor-Leste" },
  { code: "TG", name: "Togo" },
  { code: "TK", name: "Tokelau" },
  { code: "TO", name: "Tonga" },
  { code: "TT", name: "Trinidad and Tobago" },
  { code: "TN", name: "Tunisia" },
  { code: "TR", name: "Turkey" },
  { code: "TM", name: "Turkmenistan" },
  { code: "TC", name: "Turks and Caicos Islands" },
  { code: "TV", name: "Tuvalu" },

  { code: "UG", name: "Uganda" },
  { code: "UA", name: "Ukraine" },
  { code: "AE", name: "United Arab Emirates" },
  { code: "GB", name: "United Kingdom" },
  { code: "US", name: "United States" },
  { code: "UY", name: "Uruguay" },
  { code: "UZ", name: "Uzbekistan" },

  { code: "VU", name: "Vanuatu" },
  { code: "VA", name: "Vatican City" },
  { code: "VE", name: "Venezuela" },
  { code: "VN", name: "Vietnam" },
  { code: "VI", name: "Virgin Islands (U.S.)" },

  { code: "WF", name: "Wallis and Futuna" },
  { code: "EH", name: "Western Sahara" },

  { code: "YE", name: "Yemen" },
  { code: "ZM", name: "Zambia" },
  { code: "ZW", name: "Zimbabwe" }
];

export const countriesUk = [
  { code: "AF", name: "Афганістан" },
  { code: "AL", name: "Албанія" },
  { code: "DZ", name: "Алжир" },
  { code: "AS", name: "Американське Самоа" },
  { code: "AD", name: "Андорра" },
  { code: "AO", name: "Ангола" },
  { code: "AI", name: "Ангілья" },
  { code: "AQ", name: "Антарктида" },
  { code: "AG", name: "Антигуа і Барбуда" },
  { code: "AR", name: "Аргентина" },
  { code: "AM", name: "Вірменія" },
  { code: "AW", name: "Аруба" },
  { code: "AU", name: "Австралія" },
  { code: "AT", name: "Австрія" },
  { code: "AZ", name: "Азербайджан" },

  { code: "BS", name: "Багамські Острови" },
  { code: "BH", name: "Бахрейн" },
  { code: "BD", name: "Бангладеш" },
  { code: "BB", name: "Барбадос" },
  { code: "BY", name: "Білорусь" },
  { code: "BE", name: "Бельгія" },
  { code: "BZ", name: "Беліз" },
  { code: "BJ", name: "Бенін" },
  { code: "BM", name: "Бермуди" },
  { code: "BT", name: "Бутан" },
  { code: "BO", name: "Болівія" },
  { code: "BA", name: "Боснія і Герцеговина" },
  { code: "BW", name: "Ботсвана" },
  { code: "BR", name: "Бразилія" },
  { code: "IO", name: "Британська Територія в Індійському Океані" },
  { code: "BN", name: "Бруней-Даруссалам" },
  { code: "BG", name: "Болгарія" },
  { code: "BF", name: "Буркіна-Фасо" },
  { code: "BI", name: "Бурунді" },

  { code: "KH", name: "Камбоджа" },
  { code: "CM", name: "Камерун" },
  { code: "CA", name: "Канада" },
  { code: "CV", name: "Кабо-Верде" },
  { code: "KY", name: "Кайманові Острови" },
  { code: "CF", name: "Центральноафриканська Республіка" },
  { code: "TD", name: "Чад" },
  { code: "CL", name: "Чилі" },
  { code: "CN", name: "Китай" },
  { code: "CX", name: "Острів Різдва" },
  { code: "CC", name: "Кокосові (Кілінг) Острови" },
  { code: "CO", name: "Колумбія" },
  { code: "KM", name: "Коморські Острови" },
  { code: "CG", name: "Конго" },
  { code: "CD", name: "Демократична Республіка Конго" },
  { code: "CK", name: "Острови Кука" },
  { code: "CR", name: "Коста-Рика" },
  { code: "CI", name: "Кот-д’Івуар" },
  { code: "HR", name: "Хорватія" },
  { code: "CU", name: "Куба" },
  { code: "CY", name: "Кіпр" },
  { code: "CZ", name: "Чеська Республіка" },

  { code: "DK", name: "Данія" },
  { code: "DJ", name: "Джибуті" },
  { code: "DM", name: "Домініка" },
  { code: "DO", name: "Домініканська Республіка" },

  { code: "EC", name: "Еквадор" },
  { code: "EG", name: "Єгипет" },
  { code: "SV", name: "Сальвадор" },
  { code: "GQ", name: "Екваторіальна Гвінея" },
  { code: "ER", name: "Еритрея" },
  { code: "EE", name: "Естонія" },
  { code: "SZ", name: "Есватіні" },
  { code: "ET", name: "Ефіопія" },

  { code: "FJ", name: "Фіджі" },
  { code: "FI", name: "Фінляндія" },
  { code: "FR", name: "Франція" },

  { code: "GA", name: "Габон" },
  { code: "GM", name: "Гамбія" },
  { code: "GE", name: "Грузія" },
  { code: "DE", name: "Німеччина" },
  { code: "GH", name: "Гана" },
  { code: "GI", name: "Гібралтар" },
  { code: "GR", name: "Греція" },
  { code: "GL", name: "Гренландія" },
  { code: "GD", name: "Гренада" },
  { code: "GU", name: "Гуам" },
  { code: "GT", name: "Гватемала" },
  { code: "GG", name: "Гернсі" },
  { code: "GN", name: "Гвінея" },
  { code: "GW", name: "Гвінея-Бісау" },
  { code: "GY", name: "Гаяна" },

  { code: "HT", name: "Гаїті" },
  { code: "HN", name: "Гондурас" },
  { code: "HK", name: "Гонконг" },
  { code: "HU", name: "Угорщина" },

  { code: "IS", name: "Ісландія" },
  { code: "IN", name: "Індія" },
  { code: "ID", name: "Індонезія" },
  { code: "IR", name: "Іран" },
  { code: "IQ", name: "Ірак" },
  { code: "IE", name: "Ірландія" },
  { code: "IM", name: "Острів Мен" },
  { code: "IL", name: "Ізраїль" },
  { code: "IT", name: "Італія" },

  { code: "JM", name: "Ямайка" },
  { code: "JP", name: "Японія" },
  { code: "JE", name: "Джерсі" },
  { code: "JO", name: "Йорданія" },

  { code: "KZ", name: "Казахстан" },
  { code: "KE", name: "Кенія" },
  { code: "KI", name: "Кірібаті" },
  { code: "KP", name: "Північна Корея" },
  { code: "KR", name: "Південна Корея" },
  { code: "KW", name: "Кувейт" },
  { code: "KG", name: "Киргизстан" },

  { code: "LA", name: "Лаос" },
  { code: "LV", name: "Латвія" },
  { code: "LB", name: "Ліван" },
  { code: "LS", name: "Лесото" },
  { code: "LR", name: "Ліберія" },
  { code: "LY", name: "Лівія" },
  { code: "LI", name: "Ліхтенштейн" },
  { code: "LT", name: "Литва" },
  { code: "LU", name: "Люксембург" },

  { code: "MO", name: "Макао" },
  { code: "MG", name: "Мадагаскар" },
  { code: "MW", name: "Малаві" },
  { code: "MY", name: "Малайзія" },
  { code: "MV", name: "Мальдіви" },
  { code: "ML", name: "Малі" },
  { code: "MT", name: "Мальта" },
  { code: "MH", name: "Маршаллові Острови" },
  { code: "MQ", name: "Мартиніка" },
  { code: "MR", name: "Мавританія" },
  { code: "MU", name: "Маврикій" },
  { code: "MX", name: "Мексика" },
  { code: "FM", name: "Мікронезія" },
  { code: "MD", name: "Молдова" },
  { code: "MC", name: "Монако" },
  { code: "MN", name: "Монголія" },
  { code: "ME", name: "Чорногорія" },
  { code: "MS", name: "Монтсеррат" },
  { code: "MA", name: "Марокко" },
  { code: "MZ", name: "Мозамбік" },
  { code: "MM", name: "Мʼянма" },

  { code: "NA", name: "Намібія" },
  { code: "NR", name: "Науру" },
  { code: "NP", name: "Непал" },
  { code: "NL", name: "Нідерланди" },
  { code: "NZ", name: "Нова Зеландія" },
  { code: "NI", name: "Нікарагуа" },
  { code: "NE", name: "Нігер" },
  { code: "NG", name: "Нігерія" },
  { code: "NU", name: "Ніуе" },
  { code: "NF", name: "Острів Норфолк" },
  { code: "MK", name: "Північна Македонія" },
  { code: "MP", name: "Північні Маріанські Острови" },
  { code: "NO", name: "Норвегія" },

  { code: "OM", name: "Оман" },

  { code: "PK", name: "Пакистан" },
  { code: "PW", name: "Палау" },
  { code: "PS", name: "Палестина" },
  { code: "PA", name: "Панама" },
  { code: "PG", name: "Папуа-Нова Гвінея" },
  { code: "PY", name: "Парагвай" },
  { code: "PE", name: "Перу" },
  { code: "PH", name: "Філіппіни" },
  { code: "PL", name: "Польща" },
  { code: "PT", name: "Португалія" },

  { code: "PR", name: "Пуерто-Рико" },

  { code: "QA", name: "Катар" },

  { code: "RE", name: "Реюньйон" },
  { code: "RO", name: "Румунія" },
  { code: "RU", name: "Росія" },
  { code: "RW", name: "Руанда" },

  { code: "WS", name: "Самоа" },
  { code: "SM", name: "Сан-Марино" },
  { code: "ST", name: "Сан-Томе і Принсіпі" },
  { code: "SA", name: "Саудівська Аравія" },
  { code: "SN", name: "Сенегал" },
  { code: "RS", name: "Сербія" },
  { code: "SC", name: "Сейшельські Острови" },
  { code: "SL", name: "Сьєрра-Леоне" },
  { code: "SG", name: "Сінгапур" },
  { code: "SK", name: "Словаччина" },
  { code: "SI", name: "Словенія" },
  { code: "SB", name: "Соломонові Острови" },
  { code: "SO", name: "Сомалі" },
  { code: "ZA", name: "Південно-Африканська Республіка" },
  { code: "GS", name: "Південна Джорджія та Південні Сандвічеві Острови" },
  { code: "SS", name: "Південний Судан" },
  { code: "ES", name: "Іспанія" },
  { code: "LK", name: "Шрі-Ланка" },
  { code: "SD", name: "Судан" },
  { code: "SR", name: "Суринам" },
  { code: "SE", name: "Швеція" },
  { code: "CH", name: "Швейцарія" },
  { code: "SY", name: "Сирія" },

  { code: "TW", name: "Тайвань" },
  { code: "TJ", name: "Таджикистан" },
  { code: "TZ", name: "Танзанія" },
  { code: "TH", name: "Таїланд" },
  { code: "TL", name: "Східний Тімор" },
  { code: "TG", name: "Того" },
  { code: "TK", name: "Токелау" },
  { code: "TO", name: "Тонга" },
  { code: "TT", name: "Тринідад і Тобаго" },
  { code: "TN", name: "Туніс" },
  { code: "TR", name: "Туреччина" },
  { code: "TM", name: "Туркменістан" },
  { code: "TC", name: "Острови Теркс і Кайкос" },
  { code: "TV", name: "Тувалу" },

  { code: "UG", name: "Уганда" },
  { code: "UA", name: "Україна" },
  { code: "AE", name: "Обʼєднані Арабські Емірати" },
  { code: "GB", name: "Велика Британія" },
  { code: "US", name: "Сполучені Штати Америки" },
  { code: "UY", name: "Уругвай" },
  { code: "UZ", name: "Узбекистан" },

  { code: "VU", name: "Вануату" },
  { code: "VA", name: "Ватикан" },
  { code: "VE", name: "Венесуела" },
  { code: "VN", name: "Вʼєтнам" },
  { code: "VI", name: "Віргінські Острови (США)" },

  { code: "WF", name: "Уолліс і Футуна" },
  { code: "EH", name: "Західна Сахара" },

  { code: "YE", name: "Ємен" },
  { code: "ZM", name: "Замбія" },
  { code: "ZW", name: "Зімбабве" }
];
