require_relative '../../node_modules/@capacitor/ios/scripts/pods_helpers'

platform :ios, '14.0'
use_frameworks!
inhibit_all_warnings!

install! 'cocoapods', :disable_input_output_paths => false

def capacitor_pods
  pod 'Capacitor', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCommunityAppleSignIn', :path => '../../node_modules/@capacitor-community/apple-sign-in'
  pod 'CapacitorFirebaseAnalytics', :path => '../../node_modules/@capacitor-firebase/analytics'
  pod 'CapacitorFirebaseCrashlytics', :path => '../../node_modules/@capacitor-firebase/crashlytics'
  pod 'CapacitorApp', :path => '../../node_modules/@capacitor/app'
  pod 'CapacitorDevice', :path => '../../node_modules/@capacitor/device'
  pod 'CapacitorFilesystem', :path => '../../node_modules/@capacitor/filesystem'
  pod 'CapacitorHaptics', :path => '../../node_modules/@capacitor/haptics'
  pod 'CapacitorLocalNotifications', :path => '../../node_modules/@capacitor/local-notifications'
  pod 'CapacitorPreferences', :path => '../../node_modules/@capacitor/preferences'
  pod 'CapacitorPushNotifications', :path => '../../node_modules/@capacitor/push-notifications'
  pod 'CapacitorShare', :path => '../../node_modules/@capacitor/share'
  pod 'CapacitorStatusBar', :path => '../../node_modules/@capacitor/status-bar'
  pod 'RevenuecatPurchasesCapacitor', :path => '../../node_modules/@revenuecat/purchases-capacitor'
end

target 'App' do
  capacitor_pods
  # Add your Pods here
  pod 'CapacitorFirebaseAnalytics/Analytics', :path => '../../node_modules/@capacitor-firebase/analytics'
end

post_install do |installer|
  assertDeploymentTarget(installer)

  hybrid_common_file = File.join(
    __dir__,
    'Pods',
    'PurchasesHybridCommon',
    'ios',
    'PurchasesHybridCommon',
    'PurchasesHybridCommon',
    'StoreProduct+HybridAdditions.swift'
  )

  if File.exist?(hybrid_common_file)
    File.chmod(0o644, hybrid_common_file)
    source = File.read(hybrid_common_file)
    patched = source
      .gsub('static func rc_normalized(subscriptionPeriod: SubscriptionPeriod) -> String {',
            'static func rc_normalized(subscriptionPeriod: RevenueCat.SubscriptionPeriod) -> String {')
      .gsub('static func rc_normalized(subscriptionPeriod: StoreKit.SubscriptionPeriod) -> String {',
            'static func rc_normalized(subscriptionPeriod: RevenueCat.SubscriptionPeriod) -> String {')
      .gsub('static func rc_normalized(subscriptionPeriodUnit: SubscriptionPeriod.Unit) -> String {',
            'static func rc_normalized(subscriptionPeriodUnit: RevenueCat.SubscriptionPeriod.Unit) -> String {')
      .gsub('static func rc_normalized(subscriptionPeriodUnit: StoreKit.SubscriptionPeriod.Unit) -> String {',
            'static func rc_normalized(subscriptionPeriodUnit: RevenueCat.SubscriptionPeriod.Unit) -> String {')

    if patched != source
      File.write(hybrid_common_file, patched)
    end
  end

  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['GCC_WARN_INHIBIT_ALL_WARNINGS'] = 'YES'
      config.build_settings['SWIFT_SUPPRESS_WARNINGS'] = 'YES'
    end
  end
end
